### ISSUE TITLE
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by avestoinn** [AlekseyKorshuk/yoomoney-api#4] opened 2021-09-07 10:01 UTC
It throws an error when I try to check payments status. It was stable for 3-4 days, now it throws such an error. 

```
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Sep 07 11:50:45 localhost python3.7[29515]: During handling of the above exception, another exception occurred:
Sep 07 11:50:45 localhost python3.7[29515]: Traceback (most recent call last):
Sep 07 11:50:45 localhost python3.7[29515]:   File "/usr/local/lib/python3.7/dist-packages/aiogram/dispatcher/dispatcher.py", line 409, in _process_polling_updates
Sep 07 11:50:45 localhost python3.7[29515]:     for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
Sep 07 11:50:45 localhost python3.7[29515]:   File "/usr/local/lib/python3.7/dist-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
Sep 07 11:50:45 localhost python3.7[29515]:     return await asyncio.gather(*tasks)
Sep 07 11:50:45 localhost python3.7[29515]:   File "/usr/local/lib/python3.7/dist-packages/aiogram/dispatcher/handler.py", line 116, in notify
Sep 07 11:50:45 localhost python3.7[29515]:     response = await handler_obj.handler(*args, **partial_data)
Sep 07 11:50:45 localhost python3.7[29515]:   File "/usr/local/lib/python3.7/dist-packages/aiogram/dispatcher/dispatcher.py", line 286, in process_update
Sep 07 11:50:45 localhost python3.7[29515]:     return await self.callback_query_handlers.notify(update.callback_query)
Sep 07 11:50:45 localhost python3.7[29515]:   File "/usr/local/lib/python3.7/dist-packages/aiogram/dispatcher/handler.py", line 116, in notify
Sep 07 11:50:45 localhost python3.7[29515]:     response = await handler_obj.handler(*args, **partial_data)
Sep 07 11:50:45 localhost python3.7[29515]:   File "/root/{}/handlers/general.py", line 199, in check_payment
Sep 07 11:50:45 localhost python3.7[29515]:     if payment.is_paid():
Sep 07 11:50:45 localhost python3.7[29515]:   File "/root/{}/models.py", line 91, in is_paid
Sep 07 11:50:45 localhost python3.7[29515]:     if api.is_paid(self.label):
Sep 07 11:50:45 localhost python3.7[29515]:   File "/root/{}/yandex_api.py", line 31, in is_paid
Sep 07 11:50:45 localhost python3.7[29515]:     history = client.operation_history(label=label)
Sep 07 11:50:45 localhost python3.7[29515]:   File "/usr/local/lib/python3.7/dist-packages/yoomoney/client.py", line 53, in operation_history
Sep 07 11:50:45 localhost python3.7[29515]:     details=details,
Sep 07 11:50:45 localhost python3.7[29515]:   File "/usr/local/lib/python3.7/dist-packages/yoomoney/history/history.py", line 72, in __init__
Sep 07 11:50:45 localhost python3.7[29515]:     data = self._request()
Sep 07 11:50:45 localhost python3.7[29515]:   File "/usr/local/lib/python3.7/dist-packages/yoomoney/history/history.py", line 177, in _request
Sep 07 11:50:45 localhost python3.7[29515]:     response = requests.request("POST", url, headers=headers, data=payload)
Sep 07 11:50:45 localhost python3.7[29515]:   File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 61, in request
Sep 07 11:50:45 localhost python3.7[29515]:     return session.request(method=method, url=url, **kwargs)
Sep 07 11:50:45 localhost python3.7[29515]:   File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 542, in request
Sep 07 11:50:45 localhost python3.7[29515]:     resp = self.send(prep, **send_kwargs)
Sep 07 11:50:45 localhost python3.7[29515]:   File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 655, in send
Sep 07 11:50:45 localhost python3.7[29515]:     r = adapter.send(request, **kwargs)
Sep 07 11:50:45 localhost python3.7[29515]:   File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 498, in send
Sep 07 11:50:45 localhost python3.7[29515]:     raise ConnectionError(err, request=request)
Sep 07 11:50:45 localhost python3.7[29515]: requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

```

**Comment by AlekseyKorshuk** [comment] 2021-09-07 12:56
Check this Colab: https://colab.research.google.com/drive/1-JnnhAeENS6BkoqYvHoFiDKkdZZdKBt2?usp=sharing
It works for me. The problem is on your side.

*May be the problem is while using async aiogram and sync yoomoney library.

I am closing this issue. Reopen it if needed.

**Closed by AlekseyKorshuk** 2021-09-07 12:56 UTC
